# Generated by Django 4.0.1 on 2022-01-05 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_datetime',
        ),
    ]
